#@data/values
---

features:
  enableLinkerd: true

env:
  - name: TZ
    value: America/Sao_Paulo

deployment:
  port: 8080

ingress:
  enable: true
  type: nginx
  domain:
    enable: true
    name: forattini.app
    email: filipeforattini1@gmail.com
