#@data/values
---
port: 8080

env:
  - name: PORT
    value: "8080"
  - name: TZ
    value: America/Sao_Paulo

ingress:
  enable: true
  type: traefik
  domain: forattini.app
  
  letsencrypt:
    enable: true
    email: filipeforattini1@gmail.com
